name: postboy
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      # --- FIX: Add persistent volume mapping ---
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # --- FIX: Define the named volume ---
